apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: dify
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      automountServiceAccountToken: false
      restartPolicy: Always
      containers:
      - name: web
        image: langgenius/dify-web:1.7.2
        envFrom:
          - configMapRef:
              name: dify-config
        env:
        - name: SENTRY_DSN
          valueFrom:
            configMapKeyRef:
              name: dify-config
              key: WEB_SENTRY_DSN
        ports:
        - containerPort: 3000
        startupProbe:
          exec:
            command:
              - sh
              - -c
              - "ps aux | grep -E '[c]elery.*worker' >/dev/null"
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 60

        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "ps aux | grep -E '[c]elery.*worker' >/dev/null"
          periodSeconds: 20
          timeoutSeconds: 2
          failureThreshold: 3

        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "celery inspect ping | grep -q OK"
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: dify
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: web
  type: ClusterIP
  selector:
    app: web